# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konfi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sonn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.IntegerField()),
                ('kirche', models.TextField()),
                ('datum', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='konfi',
            name='gk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Sonn'),
        ),
    ]
